language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: aulob5feCruHH1O6iV4SY78qTT3QfV1q1GjfgzgEzOmPAR8ykaGiTTE05PiLPpWi32CPKdRQldVDMQtkzc66uOJ7RhM9RL4DtXkA8d3y/k0AXjifnscCtBXk+EDMNC2wmLidfuSq34MOFe2QUs9fXXb+Te01PNcFfEqWJHNe6SW9FIfzAeGrKxVMHXSDdwlLaB94Yynkgg7TOw1ircnzEAnvZ0HTP0dyLvU+bTm1LaqPDEOybnn2UjwvTadKsy9SWk8LJAxz6KEeJ/2iso3j6Rb29F6PC7J89Ap0C/Rikc7Zj/74lcS+9/mTF2tz+ZmWX6zaS5It67Q3mN5TtWIzx4yWr9nwg9KSge7FiflOEKFbGdSmK97ykIZZ6KZG6BOytaSKDoBxr5W3Vz2SPl6MKjrdrVUVM8RpPqsY8MHhBchU27eW49SZ1cCa6aM5cTEmw0zcBwqOoYnkCFzaMF4BfbfgtUabPfWsM0fgxPlv8y8ODy4jqubSqBR18nOhcen82E4D/h79YcGvcuxgxKDEGufb3VxiL9h2l5ewszcgRoOHsGVTX7k9bbHCKhK++Bj14UOxGGM0KLuwmxs8dS3lX0hF2uOrEoeXMhDbQ2i3iejqq2HFbkoUPLpiBWVSkWRJU31nyR/xV8Z99hDGQsNy8ZqwD0hYHa935M6LBJpT/qA=
  app: pacific-scrubland-37773
  on:
    repo: thinkful-c11/full-stack-capstone-avi-sonja
